#!/usr/bin/env bash
# script that prints subdomains for a domain

# output: subdomain information
print_subdomain_info() {
  full_domain="$1"
  subdomain=${full_domain%%.*}
  answer_section=$(dig "$full_domain" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:');
  echo "$answer_section" | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}';
}


if [ $# -eq 1 ]; then
  print_subdomain_info "www.$1"
  print_subdomain_info "lb-01.$1"
  print_subdomain_info "web-01.$1"
  print_subdomain_info "web-02.$1"
else
  print_subdomain_info "$2.$1"
fi

