#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '24i\    location /redirect_me {\n        return 301 https://intranet.alxswe.com/;\n    }' /etc/nginx/sites-available/default
sudo nginx -s reload
