#!/usr/bin/env bash
# custom 404 page 

sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo bash -c "echo \"Ceci n'est pas une page\" > /var/www/html/custom404.html"
sudo sed -i '24i\        location /redirect_me {\n            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default
sudo sed -i '16i\        error_page 404 /custom404.html;' /etc/nginx/nginx.conf
sudo service nginx reload
