#!/usr/bin/env bash
# custom 404 page 

sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'printf "Ceci n'\''est pas une page\n" > /var/www/html/404.html'
sudo sed -i '24i\    location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\t\t\n}\n\t\terror_page 404             /404.html;\n' /etc/nginx/sites-available/default
sudo service nginx reload
