#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sh -c 'echo "frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 331788-web-01 54.197.131.212:80
    server 331788-web-02 52.87.155.82:80" > /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
