#!/usr/bin/env bash
# 9. Process and PID file

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'" 15
trap "echo 'Y U no love me?!'" 2
trap "rm /var/run/myscript.pid" 3 15

while true; do
	echo "To infinity and beyond"
	sleep 2
done

# SIGTERM 15
# SIGINT  2
# SIGQUIT 3
