#!/usr/bin/env bash
# loop for items in directory, cut the name only

for file in *; do
	if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
		name=$(echo "$file" | cut -d "-" -f2-)
		echo "$name"
	fi
done
