#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

sudo cp /etc/hosts /tmp/hosts.new
sudo cp /etc/hosts /etc/hosts.backup
sudo sed -i "s/127.0.0.1/127.0.0.2/g" /tmp/hosts.new
echo -e "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
sudo cp -f /tmp/hosts.new /etc/hosts
