#!/usr/bin/env bash
# run nginx as another user

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
